### ISSUE TITLE
format on mobile 

### ISSUE THREAD

**Issue by diePaulina** [TrAInConnectionPrediction/tcp#107]
Die Bahnhof boxen sind außerhalb der grauen hintergrund box auf dem handy (bei Firefox und Chrome)

**Comment by McToel** [comment]
Kannst du bitte die Version hier mal ausprobieren? Da sollte das jetzt gefixt sein: https://next.trainconnectionprediction.de/

**Comment by mariusdkm** [comment]
![Screenshot 2022-01-20 at 23 30 03](https://user-images.githubusercontent.com/43829743/150432461-d9e14798-8011-4feb-a25b-b526f33a8f3f.png)

Auf Mobile sieht's gut aus, aber bei der Datumsanzeige ist des Icon noch nicht in der Richtigen größe, auf Mobile und auf Desktop, siehe Screenshot

**Comment by diePaulina** [comment]
> Kannst du bitte die Version hier mal ausprobieren? Da sollte das jetzt gefixt sein: https://next.trainconnectionprediction.de/

Ja jetzt sieht es gut aus

**Comment by McToel** [comment]
Reopen, da das Problem auf Master noch nicht gefixt ist.
