### ISSUE TITLE
Css Fehler wenn das trailing slash fehlt

### ISSUE THREAD

**Issue by her-finn** [TrAInConnectionPrediction/tcp#25]
Es gibt einen CSS-Fehler wenn das trailing slash fehlt: http://kepiserver.de/tcp

**Comment by McToel** [comment]
Dass scheint mir nicht nur css zu sein. @mariusdkm Was denkst du?

**Comment by mariusdkm** [comment]
Des ist HTML und JS, weil die Einbingung der Dateien relativ und nicht absolut sind, damit man die Dateien vom eigenen Rechner einbinden kann und nicht die vom Server nimmt. 
Kann man aber denke ich relativ einfach fixen.
Ich schaus mir morgen an.
